### ISSUE TITLE
Consertar texto do total de gasto em obras

### ISSUE THREAD

**Issue by marcuswac** [analytics-ufcg/obras-pb#189]
O texto atual é:

> 3626704910.12
> Foi o Total Gasto em Obras (A partir de 2012)

O que pode melhorar:

- O valor muito grande sem separador fica pouco legível. Você pode separar o número com ponto e os decimais com vírgula, além de adicionar o símbolo da moeda. Talvez tenha opção de formatar o número como currency de alguma forma, indicando o símbolo e os separadores. Exemplo: R$3.626.704.910,12.

- O texto está muito grande e fica estranho em telas que não são wide. Você pode colocar apenas: _R$3.626.704.910,12 Gasto em Obras*_
Em algum outro lugar você pode colocar a observação:
_* Obras a partir de 1 de janeiro de 2012_

**Comment by silveiraluiza** [comment]
Feito!
