### ISSUE TITLE
Aumentar range default do período de tempo nos gráficos acumulados e em barras

### ISSUE THREAD

**Issue by marcuswac** [analytics-ufcg/obras-pb#191]
Em muitos gráficos o período default é de apenas 6 meses (janeiro a junho). O ideai é termos como default 13 meses (o último mês + os 12 meses meses anteriores cadastrados no BD). Exemplo: de junho de 2017 a junho de 2018.

**Comment by silveiraluiza** [comment]
feito! nos gráficos de custos por ano coloquei 4 anos como sugerisse também (menos no de tipos por conta de cubati)
