### ISSUE TITLE
Modificar texto nos Gauges dos custos

### ISSUE THREAD

**Issue by marcuswac** [analytics-ufcg/obras-pb#192]
Atualmente, o gauge com os investimentos em obras em andamento e finalizadas mostra "2.1G" e "1.4G". O ideal é que tenha um formato de moeda, com R$2,... e R$1,4... Esse "G" é pouco intuitivo. Se for bilhões, TALVEZ 2.1B ou 2.1 Bi seja aceitável.

**Comment by silveiraluiza** [comment]
Feito!
