### ISSUE TITLE
Melhorar as cores de preenchimento no gráfico de area stacked dos tipos de obras

### ISSUE THREAD

**Issue by marcuswac** [analytics-ufcg/obras-pb#193]
As cores dos dygraphs que deveriam mostrar a área de cada tipo de obra estão ruins. Não dá pra notar que é um gráfico de área stacked; parece gráfico de linhas. Você tem que colocar cores mais marcantes no "fill" para cada tipo de obra, como mostra o exemplo de "Stacked" do dygraph: https://rstudio.github.io/dygraphs/

**Comment by silveiraluiza** [comment]
Opacidade das cores ajustada.
