### ISSUE TITLE
Mudar de porcentagem para valor absoluto no mapa de custos por município

### ISSUE THREAD

**Issue by marcuswac** [analytics-ufcg/obras-pb#194]
Atualmente a legenda do mapa apresenta valores em porcentagem para o custo das obras por município. O ideal é que lá apareça valores absolutos. Eu imagino que os valores possuam alguns outliers, então alguns municípios podem ficar muito "quentes" e vários outros da mesma cor. Para evitar isso, talvez seja melhor usar uma escala de log ou criar as faixas de valores na mão. 

Uma possível escala "manual" com 8 níveis:
```
0 - 100.000
100.000 - 500.000
500.000 - 1.000.000
1.000.000 - 5.000.000
5.000.000 - 10.000.000
10.000.000 - 50.000.000
50.000.000 - 100.000.000
100.000.000+
```

**Comment by silveiraluiza** [comment]
Feito! Mas vou reabrir essa issue após a reunião de amanhã, para fazer com uma função ao invés de manualmente
