### ISSUE TITLE
No painel de tipos de obras, criar scatter plots de Dimensão x Custo da obra

### ISSUE THREAD

**Issue by marcuswac** [analytics-ufcg/obras-pb#195]
Fazer um scatter plot para cada unidade de medida (m2, m3, m, km), com a dimensão da obra no eixo-x e o custo da obra do eixo-y. A cor dos pontos deve ser de acordo com o Tipo de obra. E ao passar o mouse em cima de um ponto, deve-se indicar qual o município da obra, o valor, a dimensão e sua descrição.

**Comment by silveiraluiza** [comment]
Feito!
