### ISSUE TITLE
Adicionar mais dados na tabela do "Ranking de tipo de obras"

### ISSUE THREAD

**Issue by marcuswac** [analytics-ufcg/obras-pb#198]
A tabela hoje em dia mostra dados genéricos de quantidade e custos por tipo de obra. O ideal é que a gente tenha informação por município, para ser possível compará-los.

Colunas que a tabela deve ter:
Tipo de Obra, Município, Quantidade de obras, Unidade de medida, Custo unitário médio*, Custo total 

Ordenar por: `arrange(Tipo_de_Obra, desc(Custo_unitário_médio))`

* Custo unitário é o custo total dividido pela dimensão.

**Comment by silveiraluiza** [comment]
Feito!
